name: mawa_api
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.3
  flutter: ">=1.17.0"

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.15
  http: ^0.13.4

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
